#!/bin/bash

download_discord () {
    sudo mkdir /opt/temp
    sudo curl -L "https://discord.com/api/download?platform=linux&format=tar.gz" -o /opt/temp/discord.tar.gz
}

install_discord () {
    download_discord
    sudo tar -xvzf /opt/temp/discord.tar.gz -C /opt
    sudo ln -sf /opt/Discord/Discord /usr/bin/discord
    cat << EOF | sudo tee /usr/share/applications/discord.desktop
    [Desktop Entry]
    Name=Discord
    StartupWMClass=discord
    Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
    GenericName=Internet Messenger
    Exec=/usr/bin/discord
    Icon=/opt/Discord/discord.png
    Type=Application
    Categories=Network;InstantMessaging;
    Path=/usr/bin
EOF
    sudo rm -rf /opt/temp
}

remove_discord () {
    rm -r ~/.config/discord
    sudo rm -rf /opt/Discord
    sudo rm /usr/bin/Discord
    sudo rm /usr/share/applications/discord.desktop
}

update_discord () {
    sudo rm -rf /opt/Discord
    sudo rm /usr/bin/Discord
    sudo rm /usr/share/applications/discord.desktop
    install_discord
}



if [ "$1" == "install" ]; then
    install_discord
    echo "Discord is now installed"
    exit
fi

if [ "$1" == "update" ]; then
    update_discord
    echo "Discord is now updated"
    exit
fi

if [ "$1" == "uninstall" ]; then
    remove_discord
    echo "Discord is now removed"
    exit
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "-h    --help    Show this page"
    echo "install         Install Discord"
    echo "uninstall       Remove Discord    (Only if installed with this utility)"
    echo "update          Update Discord    (Only if installed with this utility)"
    exit
fi

echo "discordutility: try 'discordutility --help' for more information"
